import "./globals.css";
import LayoutTheme from "@/component/Layout/LayoutTheme";
import {yekan} from "@/utils/fonts";
import Layouts from "@/component/Layout/Layouts";


export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({children}) {
    return (
        <html lang="fa" dir="rtl">
        <body className={`${yekan.className} bg-slate-200  dark:bg-gray-800 `}>
        <Layouts>
            <LayoutTheme>
                {children}
            </LayoutTheme>
        </Layouts>
        </body>
        </html>
    );
}
